name: Build MNN Windows LLM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone MNN repository
      run: git clone https://github.com/alibaba/MNN.git 

    - name: Create build directory
      working-directory: MNN
      run: |
        mkdir build && cd build

    - name: CMake for MNN
      working-directory: MNN/build
      run: |
        cmake .. -DMNN_LOW_MEMORY=true -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true -DMNN_BUILD_LLM=true -DMNN_SUPPORT_TRANSFORMER_FUSE=true -DCMAKE_CXX_FLAGS="/source-charset:utf-8 /EHsc"
    
    - name: Build llm_demo
      working-directory: MNN/build
      run: |
        cmake --build . --config Release --target llm_demo -- /p:WarningLevel=3 /p:TreatWarningsAsErrors=false
    - name: Package build directory
      run: |
        Compress-Archive -Path MNN\build\* -DestinationPath llm.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-llm
        path: llm.zip
