name: Build pic-smaller and Download Dist

on:
  workflow_dispatch: # 允许手动运行构建任务

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用与项目兼容的 Node.js 版本

      - name: Clone pic-smaller repository
        run: |
          git clone https://github.com/joye61/pic-smaller.git 
          cd pic-smaller

      - name: Install dependencies
        working-directory: pic-smaller
        run: npm install

      - name: Build project
        working-directory: pic-smaller
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pic-smaller-dist
          path: pic-smaller/dist/
