name: Build fetch-mcp and Download Dist

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone fetch-mcp
        run: |
          git clone https://github.com/zcaceres/fetch-mcp.git 
          cd fetch-mcp

      - name: Install dependencies
        working-directory: fetch-mcp
        run: npm install

      - name: Build project
        working-directory: fetch-mcp
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fetch-mcp-dist
          path: fetch-mcp/dist/
