name: Build MNN and Upload Build Artifact

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake g++ make

    - name: Clone MNN repository
      run: |
        git clone https://github.com/alibaba/MNN.git 

    - name: Create build directory
      working-directory: ./MNN
      run: |
        mkdir -p build && cd build

    - name: Configure CMake for MNN with LLM support
      working-directory: ./MNN/build
      run: |
        cmake .. \
          -DMNN_LOW_MEMORY=true \
          -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true \
          -DMNN_BUILD_LLM=true \
          -DMNN_SUPPORT_TRANSFORMER_FUSE=true \
          -DLLM_SUPPORT_VISION=true \
          -DMNN_BUILD_OPENCV=true \
          -DMNN_IMGCODECS=true \
          -DMNN_AVX512=true

    - name: Build llm_demo
      working-directory: ./MNN/build
      run: |
        make -j$(nproc) llm_demo

    - name: Compress build directory
      run: |
        cd ./MNN
        tar -czf build_artifact.tar.gz build/

    - name: Move archive to root for upload
      run: |
        mv ./MNN/build_artifact.tar.gz .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mnn_build_artifact
        path: ./build_artifact.tar.gz
