name: Build MNN LLM Demo

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clone MNN repository
        run: |
          git clone https://github.com/alibaba/MNN.git 

      - name: Install vcpkg and OpenCV
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: |
          # 安装 vcpkg
          git clone https://github.com/microsoft/vcpkg.git 
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install opencv[core,imgcodecs,highgui]:x64-windows
          cd ..

      - name: Set Environment Variables
        shell: powershell
        run: |
          $env:VCPKG_ROOT = "C:/vcpkg"
          $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"

      - name: Create Build Directory
        shell: powershell
        working-directory: ${{ github.workspace }}/MNN
        run: |
          mkdir build -Force

      - name: Configure Project with CMake (with Vision Support)
        shell: powershell
        working-directory: ${{ github.workspace }}/MNN/build
        run: |
          cmake .. -G "Visual Studio 17 2022" `
            -DCMAKE_BUILD_TYPE=Release `
            -DMNN_LOW_MEMORY=true `
            -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true `
            -DMNN_BUILD_LLM=true `
            -DMNN_SUPPORT_TRANSFORMER_FUSE=true `
            -DLLM_SUPPORT_VISION=true `
            -DMNN_BUILD_OPENCV=true `
            -DMNN_IMGCODECS=true `
            -DLLM_SUPPORT_AUDIO=true `
            -DMNN_BUILD_AUDIO=true `
            -DBUILD_MLS=true `
            -DCMAKE_CXX_FLAGS="/D_USE_MATH_DEFINES /EHsc" `
            -DCMAKE_PREFIX_PATH="$env:VCPKG_ROOT/installed/x64-windows"

      - name: Build All Demos
        working-directory: ${{ github.workspace }}/MNN/build
        run: |
          cmake --build . --config Release

      - name: Check if transformerDemo.out.exe exists
        shell: powershell
        working-directory: ${{ github.workspace }}/MNN/build
        run: |
          if (Test-Path "./Release/transformerDemo.out.exe") {
            Write-Output "✅ transformerDemo.out.exe built successfully!"
          } else {
            Write-Error "❌ Failed to build transformerDemo.out.exe"
          }

      - name: Package Binaries
        shell: powershell
        working-directory: ${{ github.workspace }}
        env:
          DATE: $(Get-Date -Format "yyyyMMdd")
        run: |
          $version = Get-Date -Format "yyyyMMdd"
          Compress-Archive -Path "./MNN/build/Release/*" -DestinationPath "./mnn_llm_demo_$version.zip" -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mnn_llm_windows
          path: ./mnn_llm_demo_*.zip
