name: Build koodo-reader and Download Dist

on:
  workflow_dispatch: # 允许手动运行构建任务

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone repository
        run: |
          git clone https://github.com/koodo-reader/koodo-reader.git 

      - name: Setup Yarn
        working-directory: koodo-reader
        run: |
          npm install -g yarn

      - name: Install dependencies
        working-directory: koodo-reader
        run: |
          yarn install --legacy-peer-deps

      - name: Update browserslist DB (optional)
        working-directory: koodo-reader
        run: |
          npx update-browserslist-db@latest

      - name: Build project
        working-directory: koodo-reader
        run: |
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: koodo-reader-dist
          path: koodo-reader/build/
