name: Build MCP Filesystem Server and Download Dist

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone repository
        run: |
          git clone https://github.com/modelcontextprotocol/servers.git  mcp-servers
          cd mcp-servers

      - name: Install dependencies
        working-directory: mcp-servers
        run: npm install

      - name: Build filesystem server
        working-directory: mcp-servers/src/filesystem
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-filesystem-dist
          path: mcp-servers/src/filesystem/dist/
