name: Build MNN LLM Demo (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clone MNN repository
        run: |
          git clone https://github.com/alibaba/MNN.git 

      - name: Configure Project
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: |
          cd MNN
          mkdir build
          cd build
          cmake .. -DMNN_LOW_MEMORY=true -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true -DMNN_BUILD_LLM=true -DMNN_SUPPORT_TRANSFORMER_FUSE=true -DCMAKE_CXX_FLAGS="/D_USE_MATH_DEFINES"

      - name: Build Project
        shell: powershell
        working-directory: ${{ github.workspace }}/MNN/build
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ALL_BUILD.vcxproj /p:Configuration=Release

      - name: Package Binaries
        shell: powershell
        working-directory: ${{ github.workspace }}
        env:
          DATE: $(Get-Date -Format "yyyyMMdd")
        run: |
          $version = Get-Date -Format "yyyyMMdd"
          Compress-Archive -Path "./MNN/build/bin/*" -DestinationPath "./mnn_llm_demo_$version.zip" -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mnn_llm_windows
          path: ./mnn_llm_demo_*.zip
