name: Build llm_demo (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake g++ make

    - name: Clone MNN repository
      run: |
        git clone https://github.com/alibaba/MNN.git 

    - name: Create build directory
      working-directory: ./MNN
      run: |
        mkdir -p build && cd build

    - name: Configure CMake for MNN with LLM support
      working-directory: ./MNN/build
      run: |
        cmake .. \
          -DMNN_LOW_MEMORY=true \
          -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true \
          -DMNN_BUILD_LLM=true \
          -DMNN_SUPPORT_TRANSFORMER_FUSE=true

    - name: Build llm_demo
      working-directory: ./MNN/build
      run: |
        make -j$(nproc) llm_demo

    - name: Find and show llm_demo location
      working-directory: ./MNN/build
      run: |
        find . -type f -name "llm_demo" -exec ls -l {} \;

    - name: Save path to llm_demo
      id: find_binary
      working-directory: ./MNN/build
      run: |
        BINARY_PATH=$(find . -type f -name "llm_demo")
        echo "::set-output name=path::$BINARY_PATH"

    - name: Upload llm_demo as artifact
      uses: actions/upload-artifact@v4
      with:
        name: llm_demo
        path: ${{ steps.find_binary.outputs.path }}
