name: Build MNN LLM Demo (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Build Tools
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          cmake
          make
          mingw-w64-x86_64-toolchain

    - name: Clone MNN Repository
      shell: msys2 {0}
      run: git clone https://github.com/alibaba/MNN.git

    - name: Create Build Directory
      shell: msys2 {0}
      working-directory: ./MNN
      run: mkdir -p build

    - name: Configure CMake (MinGW)
      shell: msys2 {0}
      working-directory: ./MNN/build
      run: |
        cmake .. \
          -G "MinGW Makefiles" \
          -DMNN_LOW_MEMORY=ON \
          -DMNN_CPU_WEIGHT_DEQUANT_GEMM=ON \
          -DMNN_BUILD_LLM=ON \
          -DMNN_SUPPORT_TRANSFORMER_FUSE=ON \
          -DMNN_BUILD_VISUAL=ON \
          -DMNN_BUILD_AUDIO=ON

    - name: Build LLM Demo (MinGW)
      shell: msys2 {0}
      working-directory: ./MNN/build
      run: make -j$(nproc) llm_demo

    - name: Package Artifacts
      shell: cmd
      run: |
        7z a -ttar build_artifact.tar .\MNN\build\*
        7z a -tgzip build_artifact.tar.gz build_artifact.tar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mnn_windows_build
        path: build_artifact.tar.gz
